config/routes.rb
Rails.application.routes.draw do

  get 'days/create'

  patch 'days/destory'

  get 'class_slots/create'

  get 'class_slots/destory'

  patch 'buddy_slots/create'

  patch 'buddy_slots/edit'

  get 'buddy_slots/destory'

  resources :ds_classes

  resources :buddy_walks

  get 'articles/edit'

  get 'articles/update'

  root 'static_pages#home'

  resources :events do
    resources :time_slots, only: [:create, :destroy]
    member do
      put 'register'
      put 'unregister'
    end
  end

  resources :buddy_walks do
    resources :buddy_slots, only: [:create, :destroy]
    member do
      put 'register'
      put 'unregister'
    end
  end

  resources :ds_classes do
    resources :class_slots, only: [:create, :edit, :destroy]
    member do
      put 'register'
      put 'unregister'
    end
  end

  resources :class_slot do
    resources :days, only: [:create, :destroy]
    member do
    end
  end

  get    'home'   => 'static_pages#home'
  get    'calendar' => 'static_pages#calendar'
  get    'edit_text_box' => 'static_pages#edit_text_box'
  get    'checkin' => 'users#checkin'
  get    'checkin_class' => 'users#checkin_class'
  get    'checkin_buddy_walk' => 'users#checkin_buddy_walk'
  get    'give_staff_role' => 'users#give_staff_role'
  get    'remove_staff_role' => 'users#remove_staff_role'
  get    'schedule_buddy_walk' => 'buddy_walks#schedule'
  get    'edit_schedule_buddy_walk' => 'buddy_walks#edit_schedule'
  post    'schedule_update' => 'buddy_walks#schedule_update'
  patch    'edit_schedule_update' => 'buddy_walks#edit_schedule_update'

  get    'signup' => 'users#new'
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get     'registration_confirmation'=> 'users#registration_confirmation', as: 'reg'

  get    'searchresults_events'     => 'events#search',        as: 'events_search'
  get    'searchresults_users'      => 'users#search',         as: 'users_search'
  get    'searchresults_classes'      => 'ds_classes#search',  as: 'classes_search'
  get    'searchresults_buddy_walk_users/:id'      => 'buddy_walks#roster_search',  as: 'buddy_walk_user_search'
  
  get    'events/:id/roster'        => 'events#show_roster',   as: 'roster_of_event'
  get    'events/:id/add_time_slot' => 'events#add_time_slot', as: 'add_time_slot_to_event'

  get    'buddy_walks/:id/roster'        => 'buddy_walks#show_roster',   as: 'roster_of_buddy_walk'
  get    'add_buddy_slot' => 'buddy_walks#add_buddy_slot', as: 'add_buddy_slot_to_buddy_walks'
  get    'edit_buddy_slot' => 'buddy_walks#edit_buddy_slot', as: 'edit_buddy_slot_of_buddy_walks'

  get    'ds_classes/:id/roster'        => 'ds_classes#show_roster',   as: 'roster_of_ds_class'
  get    'ds_classes/:id/add_time_slot' => 'ds_classes#add_time_slot', as: 'add_time_slot_to_ds_class'
  
  get    'ds_classes/:class_id/class_slot/:class_slot_id/add_day'  => 'class_slots#add_day', as: 'add_day_to_class_slot'
  get    'ds_classes/:class_id/class_slot/:class_slot_id/remove_day'  => 'class_slots#remove_day', as: 'remove_day_from_class_slot'

  resources :users do
    member do
      get 'registrations' => 'users#show_registrations'
    end
  end

  resources :account_activations, only: [:new, :create, :edit, :update]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :articles, only: [:edit, :update]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @article_top = Article.find_by_id(1)
    @article_bottom = Article.find_by_id(2)
  end

  def calendar
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @events_by_date = Event.all.group_by(&:date)
    @events_by_date.reverse_merge!(BuddyWalk.all.group_by(&:date))
  end
end

app/views/static_pages/calendar.html.erb
<%= provide(:title, 'Calendar' ) %>

<div class="row">
  <div class="col-xs-12 col-sm-10 col-sm-offset-1 text-center jumbotron">
    <h1>Calendar</h1>
    <p>Note: Classes are not on this calendar. The dates for the classes are unique for each class. Please visit <%= link_to ds_classes_path do %>the classes page<% end %> for more info</p>
    <div class="well controls">
      <%= link_to calendar_path(date: @date - 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-backward"></i>
      <% end %>
      <%= "#{@date.strftime("%B")} #{@date.year}" %>
      <%= link_to calendar_path(date: @date + 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-forward"></i>
      <% end %>
    </div>

    <%= calendar @date do |date| %>
      <% if date.month == @date.month %>
        <%= date.day %><br>
        <% if @events_by_date[date] %>
          <% @events_by_date[date].each do |event| %>
            <%= link_to event.title, event %>
          <% end %>
        <% end %>
      <% else %>
        <br>
      <% end %>
    <% end %>
  </div>
</div>

app/views/static_pages/home.html.erb
<%= provide(:title, 'Home' ) %>

<div class="row">
  <div class="col-xs-12 col-sm-10 col-sm-offset-1 center jumbotron">
    <h1>Event Registration</h1>
    
    <div class="hidden-xs">
    <div align="center">
      &#8201
      &#8201
      <%= link_to "Volunteer", events_path, class: "btn btn-info btn-md home-page" %>
      &nbsp
      <%= link_to "Classes", ds_classes_path, class: "btn btn-info btn-md home-page" %>
      &nbsp
      <%= link_to "Buddy Walk", buddy_walks_path, class: "btn btn-info btn-md home-page" %>
    </div>
    <% unless logged_in? %>
    <p></p>
    <div align="center">
        <%= link_to "Sign up", signup_path, class: "btn btn-primary btn-md home-page" %>
        &nbsp
        <%= link_to "Log in", login_path, class: "btn btn-primary btn-md home-page" %>
        &nbsp
    </div>
    <% end %>
    </div>

    <div class="visible-xs-inline">
      <div align="center">
        &#8201
        &#8201
        <%= link_to "Volunteer", events_path, class: "btn btn-info btn-sm home-page" %>
        &nbsp
        <%= link_to "Classes", ds_classes_path, class: "btn btn-info btn-sm home-page" %>
        &nbsp
        <%= link_to "Buddy Walk", buddy_walks_path, class: "btn btn-info btn-sm home-page" %>
      </div>
      <div class="col-xs-12"><p></p></div>
      <% unless logged_in? %>
        <p></p>
         <div align="center">
        <%= link_to "Sign up", signup_path, class: "btn btn-primary btn-sm home-page" %>
        &nbsp
        <%= link_to "Log in", login_path, class: "btn btn-primary btn-sm home-page" %>
        &nbsp
      </div>
      <% end %>
    </div>
  </div>
</div>

<% if logged_in? && current_user.admin? %>
  <%= link_to "Edit Text", { action: :edit, controller: :articles, id: 1 }, class: "btn btn-primary home-page" %>
<% end %>

<div class="row">
  <div class="col-xs-12 col-sm-10 col-sm-offset-1 jumbotron">
    <div><%= @article_top.text.html_safe %></div>
  </div>
</div>

<% if logged_in? && current_user.admin? %>
  <%= link_to "Edit Text", { action: :edit, controller: :articles, id: 2 }, class: "btn btn-primary home-page" %>
<% end %>

<div class="row">
  <div class="col-xs-12 col-sm-10 col-sm-offset-1 jumbotron">
    <div><%= @article_bottom.text.html_safe %></div>
  </div>
</div>