config/routes.rb
Rails.application.routes.draw do

  get 'days/create'

  patch 'days/destory'

  get 'class_slots/create'

  get 'class_slots/destory'

  patch 'buddy_slots/create'

  patch 'buddy_slots/edit'

  get 'buddy_slots/destory'

  resources :ds_classes

  resources :buddy_walks

  get 'articles/edit'

  get 'articles/update'

  root 'static_pages#home'

  resources :events do
    resources :time_slots, only: [:create, :destroy]
    member do
      put 'register'
      put 'unregister'
    end
  end

  resources :buddy_walks do
    resources :buddy_slots, only: [:create, :destroy]
    member do
      put 'register'
      put 'unregister'
    end
  end

  resources :ds_classes do
    resources :class_slots, only: [:create, :edit, :destroy]
    member do
      put 'register'
      put 'unregister'
    end
  end

  resources :class_slot do
    resources :days, only: [:create, :destroy]
    member do
    end
  end

  get    'home'   => 'static_pages#home'
  get    'calendar' => 'static_pages#calendar'
  get    'edit_text_box' => 'static_pages#edit_text_box'
  get    'checkin' => 'users#checkin'
  get    'checkin_class' => 'users#checkin_class'
  get    'checkin_buddy_walk' => 'users#checkin_buddy_walk'
  get    'give_staff_role' => 'users#give_staff_role'
  get    'remove_staff_role' => 'users#remove_staff_role'
  get    'schedule_buddy_walk' => 'buddy_walks#schedule'
  get    'edit_schedule_buddy_walk' => 'buddy_walks#edit_schedule'
  post    'schedule_update' => 'buddy_walks#schedule_update'
  patch    'edit_schedule_update' => 'buddy_walks#edit_schedule_update'

  get    'signup' => 'users#new'
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get     'registration_confirmation'=> 'users#registration_confirmation', as: 'reg'

  get    'searchresults_events'     => 'events#search',        as: 'events_search'
  get    'searchresults_users'      => 'users#search',         as: 'users_search'
  get    'searchresults_classes'      => 'ds_classes#search',  as: 'classes_search'
  get    'searchresults_buddy_walk_users/:id'      => 'buddy_walks#roster_search',  as: 'buddy_walk_user_search'
  
  get    'events/:id/roster'        => 'events#show_roster',   as: 'roster_of_event'
  get    'events/:id/add_time_slot' => 'events#add_time_slot', as: 'add_time_slot_to_event'

  get    'buddy_walks/:id/roster'        => 'buddy_walks#show_roster',   as: 'roster_of_buddy_walk'
  get    'add_buddy_slot' => 'buddy_walks#add_buddy_slot', as: 'add_buddy_slot_to_buddy_walks'
  get    'edit_buddy_slot' => 'buddy_walks#edit_buddy_slot', as: 'edit_buddy_slot_of_buddy_walks'

  get    'ds_classes/:id/roster'        => 'ds_classes#show_roster',   as: 'roster_of_ds_class'
  get    'ds_classes/:id/add_time_slot' => 'ds_classes#add_time_slot', as: 'add_time_slot_to_ds_class'
  
  get    'ds_classes/:class_id/class_slot/:class_slot_id/add_day'  => 'class_slots#add_day', as: 'add_day_to_class_slot'
  get    'ds_classes/:class_id/class_slot/:class_slot_id/remove_day'  => 'class_slots#remove_day', as: 'remove_day_from_class_slot'

  resources :users do
    member do
      get 'registrations' => 'users#show_registrations'
    end
  end

  resources :account_activations, only: [:new, :create, :edit, :update]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :articles, only: [:edit, :update]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :appointments
  has_many :time_slots, through: :appointments
  has_many :class_slots, through: :appointments
  has_many :buddy_slots, through: :appointments
  has_many :events, through: :time_slots
  has_many :buddy_walks, through: :buddy_slots
  has_many :ds_classes, through: :class_slots

  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest

  validates :name,  presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password

  validates :password, length: { minimum: 6 }, allow_blank: true
  validates :address, presence: true, length: {maximum: 100}

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def self.search(search)
    where('lower(name) LIKE ? OR lower(email) LIKE ?', "%#{search.downcase}%", "%#{search.downcase}%")
  end

  def appointment(timeslot)
    appointment = Appointment.where(user_id: self.id, time_slot_id: timeslot.id).first
  end

  def appointment_class(class_slot)
    appointment = Appointment.where(user_id: self.id, class_slot_id: class_slot.id).first
  end

  def appointment_buddy(buddy_slot)
    appointment = Appointment.where(user_id: self.id, buddy_slot_id: buddy_slot.id).first
  end
 
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # Register an event
  def register(event)
    self.events << event
  end
  
  def register(buddy_walk)
    self.buddy_walks << buddy_walk
  end

private
    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:index, :destroy, :give_staff_role, :remove_staff_role]
  before_action :staff_user,     only: [:checkin, :checkin_class, :checkin_buddy_walk]



  def index
    @users = User.all
    if params[:query]
      @users = User.search(params[:query])

      url = "/searchresults_users?query=" + params[:query]
      redirect_to url
    else
      @users = []
    end

    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    unless logged_in?
  	  @user = User.new
    else
      redirect_to user_path(current_user)
    end
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
    

    session[:user_id] = @user.id
      @user.send_activation_email
     # flash[:info] = "Please check your email to activate your account."
     redirect_to reg_url
     @user.send_activation_email
    else
      render 'new'
    end
  end

def registration_confirmation
    #temp = session[:user_id]
   # id = temp
    
    #@user= User.new  
   @user = User.new
   @u = User.find(session[:user_id])
   
    #@user.send_activation_email
     #if @u.save
   # @u.send_activation_email
   # end
  
  
  end


  def search
    @users = User.all
    if params[:query]
      @users = User.search(params[:query])
    else
      @users = []
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
        flash[:success] = "Profile updated"
        redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def show_registrations
    user = User.find(params[:id])
    @registrations = user.time_slots
    @class_slots = user.class_slots
    @buddy_slots = user.buddy_slots
  end

  def checkin
    appointment = Appointment.where(:user_id => params[:id], :time_slot_id => params[:timeslot_id]).first
    appointment.update_attributes(:is_checkedin => true)
    redirect_to roster_of_event_url(params[:event_id])
  end

  def checkin_class
    appointment = Appointment.where(:user_id => params[:id], :class_slot_id => params[:class_slot_id]).first
    appointment.update_attributes(:is_checkedin => true)
    redirect_to roster_of_ds_class_url(params[:ds_class_id])
  end

  def checkin_buddy_walk
    appointment = Appointment.where(:user_id => params[:id], :buddy_slot_id => params[:buddy_slot_id]).first
    appointment.update_attributes(:is_checkedin => true)
    redirect_to roster_of_buddy_walk_url(params[:buddy_walk_id])
  end

  def give_staff_role
    user = User.find(params[:id])
    user.update_attributes(:staff => true)
    redirect_to users_url
  end

  def remove_staff_role
    user = User.find(params[:id])
    user.update_attributes(:staff => false)
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name,
                                   :email,
                                   :password,
                                   :password_confirmation,
                                   :address,
                                   :phone_number,
                                   :emergency_contact_name,
                                   :emergency_contact_phone)
    end

    # Before filters

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  (<%= user.email %>)
  <% if current_user.admin? && !current_user?(user) %>
  	<% if user.staff %>
  		| <%= link_to "Remove staff role", remove_staff_role_path(:id => user.id) %>
  	<% else %>
  		| <%= link_to "Add staff role", give_staff_role_path(:id => user.id) %>
  	<% end %>
    | <%= link_to "Delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<div class="row">
  <div class="col-xs-12 col-sm-10 col-sm-offset-1 jumbotron">
    <h1>Update your profile</h1>

    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <%= form_for(@user) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>

          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>

          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>

          <%= f.label :phone %>
          <%= f.telephone_field :phone, class: 'form-control' %>

          <%= f.label :address %>
          <%= f.text_field :address, class: 'form-control' %>

          <%= f.label :emergency_contact_name %>
          <%= f.text_field :emergency_contact_name, class: 'form-control' %>

          <%= f.label :emergency_contact_phone %>
          <%= f.telephone_field :emergency_contact_phone, class: 'form-control' %>
          
          <%= link_to "Change Password",  new_password_reset_path , :class => "btn btn-primary" %>

          <%= f.submit "Save changes", class: "btn btn-primary home-page" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.haml
= provide(:title, 'Users')
%div.row
	%div.col-xs-12.col-sm-10.col-sm-offset-1.jumbotron
		%h1 All users
		%div.row
			%div.col-xs-6.col-sm-6.col-md-offset-3
				= form_for users_search_path, method: :get do |f|
					= text_field_tag :query, params[:query], :placeholder => "Enter search", class: 'form-control'
					= submit_tag "Search", name: nil, class: "btn btn-primary home-page"
					%br
		%br
		%ul.users
			= render @users.order('name ASC')
		= will_paginate

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="row">
  <div class="col-xs-12 col-sm-10 col-sm-offset-1 jumbotron">
    <h1>Sign up</h1>
      <div class="row">
        <div class="col-xs-12 col-md-6 col-md-offset-3">
          <%= form_for(@user) do |f| %>
           <%= render 'shared/error_messages', object: f.object %>

            <%= f.label :name %>
            <%= f.text_field :name, :placeholder => "First Last", class: 'form-control' %>

            <%= f.label :email %>
            <%= f.email_field :email, :placeholder => "ex. John@example.com", class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, :placeholder => "Enter password", class: 'form-control' %>

            <%= f.label :password_confirmation, "Password Confirmation" %>
            <%= f.password_field :password_confirmation, :placeholder => "Repeat password", class: 'form-control' %>

            <%= f.label :phone, "Phone Number" %>
            <%= f.telephone_field :phone, :placeholder => "ex. (979) 000-0000", class: 'form-control' %>

            <%= f.label :address %>
            <%= f.text_field :address, :placeholder => "Address, City, State, and Zip", class: 'form-control' %>

            <%= f.label :emergency_contact_name, 'Emergency Contact Name' %>
            <%= f.text_field :emergency_contact_name, :placeholder => "First Last", class: 'form-control' %>

            <%= f.label :emergency_contact_phone, 'Emergency Contact Phone' %>
            <%= f.telephone_field :emergency_contact_phone, :placeholder => "ex. (979) 000-0000", class: 'form-control' %>

            <%= f.submit "Create my account", class: "btn btn-primary home-page" %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/users/registration_confirmation.html.erb
 <!DOCTYPE html>
<html>
<head>
<style>
body {background-color:blue;}
h1   {color:yellow}
p    {color:yellow}
</style>
</head>
<body>

<h1>REGISTRATION CONFIRMATION</h1>
<p>Please check your email to activate your account before continuing.</p>


<FORM METHOD="LINK" ACTION="home">
<INPUT TYPE="submit" VALUE="Resend Email">
</FORM>

</body>
</html>

app/views/users/search.html.haml
:css
	h2{
		font-size: 30px
	}

= provide(:title, 'User Search Results')

%div.row
	%div.col-xs-12.col-sm-10.col-sm-offset-1.jumbotron
		%h1 Search for Users
		%div.row
			%div.col-xs-6.col-sm-6.col-md-offset-3
				= form_for users_search_path, method: :get do |f|
					= text_field_tag :query, params[:query], :placeholder => "Enter search", class: 'form-control'
					= submit_tag "Search", name: nil, class: "btn btn-primary home-page"
					%br

		%ul.users
			%h2	Results for '#{params[:query]}'
			%div{:align => 'right'}
				= link_to "Back to all users", users_path
			%br

			- if @users.present?
				= render @users.order('name ASC')
			- else 
				%li
					%div{:align => "center"}
						No matches. Retry the search or try a new search.
				%br
		%br
		%div{:align => 'right'}
			= link_to "Back to all users", users_path

app/views/users/show.html.erb
<% if logged_in? && (current_user?(@user) || current_user.admin) %>
<% provide(:title, @user.name) %>
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1 jumbotron">
      <div class="row">
        <aside class="col-xs-12 col-sm-6">
          <section class="user_info">
            <h1>
              <%= @user.name %>
            </h1>
            <br><br><br><br>
            <h2>Basic Infomation</h2>
            <ul>
              <li>Email: <%= @user.email %></li>
              <li>Address: <%= @user.address %></li>
              <li>Phone Number: <%= @user.phone %></li>
            </ul>
              <h2>Emergency Contact</h2>
            <ul>
              <li>Name: <%= @user.emergency_contact_name %></li>
              <li>Phone Number: <%= @user.emergency_contact_phone %></li>
            </ul>
          </section>
        </aside>
       </div>
     </div>
  </div>
<% else %>
  <div>"Access Denied"</div>
<% end %>

app/views/users/show_registrations.html.haml
= provide(:title, 'My registrations')

%div.row
  %div.col-xs-12.col-sm-10.col-sm-offset-1.jumbotron
    %h1 Registered Events
    %table.table
      %tr
        %th.col-md-6 Event
        %th.col-md-4 Time
      - @registrations.each do |registration|
        %tr
          %td.col-md-6
            = link_to registration.event.title, registration.event
          %td.col-md-4
            = registration.event.date
            %br
            #{registration.start_time.strftime("%I:%M %p")} - #{registration.end_time.strftime("%I:%M %p")}
      - @class_slots.each do |class_slot|
        %tr
          %td.col-md-6
            = link_to class_slot.ds_class.title, class_slot.ds_class
          %td.col-md-4
            #{class_slot.ds_class.start_date} - #{class_slot.ds_class.end_date}
            %br
            = render class_slot.days.reverse
            %br
            #{class_slot.start_time.strftime("%I:%M %p")} - #{class_slot.end_time.strftime("%I:%M %p")}
      - @buddy_slots.each do |buddy_slot|
        %tr
          %td.col-md-6
            = link_to buddy_slot.buddy_walk.title, buddy_slot.buddy_walk
          %td.col-md-4
            = buddy_slot.buddy_walk.date
            %br
            #{buddy_slot.start_time.strftime("%I:%M %p")} - #{buddy_slot.end_time.strftime("%I:%M %p")}