config/routes.rb
Rails.application.routes.draw do

  get 'days/create'

  patch 'days/destory'

  get 'class_slots/create'

  get 'class_slots/destory'

  patch 'buddy_slots/create'

  patch 'buddy_slots/edit'

  get 'buddy_slots/destory'

  resources :ds_classes

  resources :buddy_walks

  get 'articles/edit'

  get 'articles/update'

  root 'static_pages#home'

  resources :events do
    resources :time_slots, only: [:create, :destroy]
    member do
      put 'register'
      put 'unregister'
    end
  end

  resources :buddy_walks do
    resources :buddy_slots, only: [:create, :destroy]
    member do
      put 'register'
      put 'unregister'
    end
  end

  resources :ds_classes do
    resources :class_slots, only: [:create, :edit, :destroy]
    member do
      put 'register'
      put 'unregister'
    end
  end

  resources :class_slot do
    resources :days, only: [:create, :destroy]
    member do
    end
  end

  get    'home'   => 'static_pages#home'
  get    'calendar' => 'static_pages#calendar'
  get    'edit_text_box' => 'static_pages#edit_text_box'
  get    'checkin' => 'users#checkin'
  get    'checkin_class' => 'users#checkin_class'
  get    'checkin_buddy_walk' => 'users#checkin_buddy_walk'
  get    'give_staff_role' => 'users#give_staff_role'
  get    'remove_staff_role' => 'users#remove_staff_role'
  get    'schedule_buddy_walk' => 'buddy_walks#schedule'
  get    'edit_schedule_buddy_walk' => 'buddy_walks#edit_schedule'
  post    'schedule_update' => 'buddy_walks#schedule_update'
  patch    'edit_schedule_update' => 'buddy_walks#edit_schedule_update'

  get    'signup' => 'users#new'
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get     'registration_confirmation'=> 'users#registration_confirmation', as: 'reg'

  get    'searchresults_events'     => 'events#search',        as: 'events_search'
  get    'searchresults_users'      => 'users#search',         as: 'users_search'
  get    'searchresults_classes'      => 'ds_classes#search',  as: 'classes_search'
  get    'searchresults_buddy_walk_users/:id'      => 'buddy_walks#roster_search',  as: 'buddy_walk_user_search'
  
  get    'events/:id/roster'        => 'events#show_roster',   as: 'roster_of_event'
  get    'events/:id/add_time_slot' => 'events#add_time_slot', as: 'add_time_slot_to_event'

  get    'buddy_walks/:id/roster'        => 'buddy_walks#show_roster',   as: 'roster_of_buddy_walk'
  get    'add_buddy_slot' => 'buddy_walks#add_buddy_slot', as: 'add_buddy_slot_to_buddy_walks'
  get    'edit_buddy_slot' => 'buddy_walks#edit_buddy_slot', as: 'edit_buddy_slot_of_buddy_walks'

  get    'ds_classes/:id/roster'        => 'ds_classes#show_roster',   as: 'roster_of_ds_class'
  get    'ds_classes/:id/add_time_slot' => 'ds_classes#add_time_slot', as: 'add_time_slot_to_ds_class'
  
  get    'ds_classes/:class_id/class_slot/:class_slot_id/add_day'  => 'class_slots#add_day', as: 'add_day_to_class_slot'
  get    'ds_classes/:class_id/class_slot/:class_slot_id/remove_day'  => 'class_slots#remove_day', as: 'remove_day_from_class_slot'

  resources :users do
    member do
      get 'registrations' => 'users#show_registrations'
    end
  end

  resources :account_activations, only: [:new, :create, :edit, :update]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :articles, only: [:edit, :update]

end

app/controllers/ds_classes_controller.rb
class DsClassesController < ApplicationController
  before_action :logged_in_user, only: [:register, :unregister]
  before_action :admin_user,     only: [:new, :create, :edit, :update, :destroy, :add_time_slot]
  before_action :staff_user,     only: [:show_roster]

  def index
    @article = Article.find_by_id(5)
    @ds_classes = DsClass.all

    if params[:query]
      @ds_classes = DsClass.search(params[:query])
      url = "/searchresults_classes?query=" + params[:query]
      redirect_to url
    else
      @ds_classes = []
    end

    @ds_classes = DsClass.paginate(page: params[:page])
  end

  def search
    @ds_classes = DsClass.all
    if params[:query]
      @ds_classes = DsClass.search(params[:query])
    else
      @ds_classes = []
    end
  end

  def show
    @ds_class = DsClass.find params[:id]
    @class_slots = @ds_class.class_slots.paginate(page: params[:page])
  end

  def new
    @ds_class = DsClass.new
  end

  def create
    @ds_class = DsClass.new(ds_class_params)
    if @ds_class.save
      flash[:success] = "New class has been created."
      redirect_to ds_class_path(@ds_class)
    else
      render 'new'
    end
  end

  def edit
    @ds_class = DsClass.find params[:id]
  end

  def update
    @ds_class = DsClass.find params[:id]
    if @ds_class.update_attributes(ds_class_params)
      flash[:success] = "Class updated."
      redirect_to @ds_class
    else
      render 'edit'
    end
  end

  def destroy
    @ds_class = DsClass.find params[:id]
    @ds_class.class_slots.each do |class_slot|
      class_slot.users.each do |user|
        EventMailer.event_cancellation_class(user, class_slot).deliver
      end
    end

    @ds_class.destroy
    flash[:info] = "Class '#{@ds_class.title}' deleted."
    redirect_to ds_classes_path
  end

  def add_time_slot
    @ds_class = DsClass.find params[:id]
    @class_slots = @ds_class.class_slots.paginate(page: params[:page])
    @class_slot = @ds_class.class_slots.build
  end

  def show_roster
    @ds_class = DsClass.find(params[:id])
  end

  def register
    class_slot = ClassSlot.find(params[:class_slot_id])
    if current_user.class_slots.include?(class_slot)
      redirect_to registrations_user_path(current_user)
    else
      class_slot.remaining_capacity -= 1
      class_slot.save

      EventMailer.event_registration_class(current_user, class_slot).deliver

      current_user.class_slots << class_slot
      flash[:success] = "You have successfully registered the class."
      redirect_to registrations_user_path(current_user) 
    end
  end

  def unregister
    class_slot = ClassSlot.find(params[:class_slot_id])
    if !current_user.class_slots.include?(class_slot)
      redirect_to registrations_user_path(current_user)
    else
      class_slot.remaining_capacity += 1
      class_slot.save
      current_user.appointment_class(class_slot).destroy
      current_user.class_slots.delete(class_slot)
      flash[:success] = "You have successfully unregistered for this event."
      redirect_to registrations_user_path(current_user)
    end
  end

  private

    def ds_class_params
      params.require(:ds_class).permit(:title,
                                    :place,
                                    :description,
                                    :start_date,
                                    :end_date)
    end
end

app/helpers/ds_classes_helper.rb
module DsClassesHelper
end

app/views/ds_classes/_ds_class.html.haml
%li
  %div{:align => "left"}
    #{ds_class.start_date} - #{ds_class.end_date}:
    %div{:align => "center"}
      = link_to ds_class.title, ds_class
      - if logged_in? && current_user.admin?
        %div{:style => "float: right"}
          = link_to "Edit", edit_ds_class_path(ds_class)
          |
          = link_to "Delete", ds_class, method: :delete, data: { confirm: "You sure?" } 

app/views/ds_classes/_form.html.erb
<%= form_for(@ds_class) do |f| %>
  <% if @ds_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ds_class.errors.count, "error") %> prohibited this ds_class from being saved:</h2>

      <ul>
      <% @ds_class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ds_classes/add_time_slot.html.haml
- provide(:title, "Add class slot to #{@ds_class.title}")
%div.row
  %div.col-xs-12.col-sm-10.col-sm-offset-1.jumbotron
    %div.event_info
      %h1 #{@ds_class.title}
      %div.row
        %div.col-xs-12.col-md-6.col-md-offset-3
          %h6 Class Times
          - if @ds_class.class_slots.any?
            %ol.time_slots
              = render @class_slots
            = will_paginate @class_slots

        %div.col-xs-12.col-md-6.col-md-offset-3
          - if logged_in? && current_user.admin
            = form_for([@ds_class, @class_slot]) do |f|
              = render 'shared/error_messages', object: f.object

              = f.label :start_time, "Start Time (HH:MM AM/PM)"
              = f.text_field :start_time, class: "timepicker", :placeholder => "  Ex: 12:00 AM"

              = f.label :end_time, "End Time (HH:MM AM/PM)"
              = f.text_field :end_time, class: "timepicker", :placeholder => "  Ex: 12:00 AM"

              = f.label :total_capacity, "Capacity"
              = f.number_field :total_capacity, class: "form-control", :placeholder => "Enter capacity"

              = f.submit "Submit", class: "btn btn-primary home-page"
            %br/
            = link_to "Back", ds_class_path(@ds_class)
          -else
            Access Denied

app/views/ds_classes/edit.html.erb
<h1>Editing ds_class</h1>

<%= render 'form' %>

<%= link_to 'Show', @ds_class %> |
<%= link_to 'Back', ds_classes_path %>

app/views/ds_classes/edit.html.haml
- provide(:title, 'Edit Class')
%div.row
  %div.col-xs-12.col-sm-10.col-sm-offset-1.jumbotron
    %h1 Edit Class
    %div.row
      %div.col-xs-12.col-md-6.col-md-offset-3
        = form_for(@ds_class) do |f|
          = render 'shared/error_messages', object: f.object

          = f.label :title
          = f.text_field :title, class: 'form-control'

          = f.label :start_date, "Start Date (MM-DD-YYYY)"
          = f.text_field :start_date, class: "datepicker", :value => @ds_class.start_date.strftime("   %B %_d, %Y"), :placeholder => "  Ex: September 2, 2015"

          = f.label :end_date, "End Date (MM-DD-YYYY)"
          = f.text_field :end_date, class: "datepicker", :value => @ds_class.end_date.strftime("   %B %_d, %Y"), :placeholder => "  Ex: September 2, 2015"

          = f.label :place, "Location"
          = f.text_field :place, class: 'form-control', :placeholder => "Enter location"

          = f.label :description
          = f.text_area :description, class: 'form-control', :placeholder => "Enter description"

          = f.submit 'Save', class: 'btn btn-primary home-page'

app/views/ds_classes/index.html.haml
= provide(:title, 'Classes')

%div.row
  %div.col-xs-12.col-sm-10.col-sm-offset-1.jumbotron
    %h1 All Classes
    %div.row
      - if logged_in? && current_user.admin?
        = link_to "Edit Text", { action: :edit, controller: :articles, id: 5 }, class: "btn btn-primary home-page"
      %div.col-xs-12.col-sm-10.col-sm-offset-1.jumbotron
        %div
          = @article.text.html_safe
      %div.col-xs-6.col-sm-6.col-md-offset-3
        = form_for classes_search_path, method: :get do |f|
          = text_field_tag :query, params[:query], :placeholder => "Enter search", class: 'form-control'
          = submit_tag "Search", name: nil, class: "btn btn-primary home-page"
          %br
    %br
    %ul.events
      = render @ds_classes.sort_by &:start_date
      %br
      -if logged_in? && current_user.admin
        = link_to "Add new class", new_ds_class_path

      = will_paginate

app/views/ds_classes/new.html.erb
<h1>New ds_class</h1>

<%= render 'form' %>

<%= link_to 'Back', ds_classes_path %>

app/views/ds_classes/new.html.haml
- provide(:title, 'New class')
%div.row
  %div.col-xs-12.col-sm-10.col-sm-offset-1.jumbotron
    %h1 New Class
    %div.row
      %div.col-xs-12.col-md-6.col-md-offset-3
        = form_for(@ds_class) do |f|
          = render 'shared/error_messages', object: f.object

          = f.label :title
          = f.text_field :title, class: 'form-control'

          = f.label :start_date, "Start Date (MM-DD-YYYY)"
          = f.text_field :start_date, class: "datepicker", :placeholder => "  Ex: September 2, 2015"

          = f.label :end_date, "End Date (MM-DD-YYYY)"
          = f.text_field :end_date, class: "datepicker", :placeholder => "  Ex: September 2, 2015"

          = f.label :place, "Location"
          = f.text_field :place, class: 'form-control', :placeholder => "Enter location"

          = f.label :description
          = f.text_area :description, class: 'form-control', :placeholder => "Enter description"

          = f.submit "Create new class", class: "btn btn-primary home-page"

app/views/ds_classes/print.html.haml
%div.row
	%div.col-xs-12.col-sm-10.col-sm-offset-1.jumbrotron
		%h1 #{@ds_class.title}

		%u1#details
			%li
				Date:
				#{ds_class.start_date} - #{ds_class.end_date}
			%li
				Place:
				= @ds_class.place
			%li
				Description:
				= @ds_class.description.html_safe

		= link_to "Back", ds_classes_path

app/views/ds_classes/search.html.haml
:css
  h2{
    font-size: 30px
  }

= provide(:title, 'Classes Search Results')
%div.row
  %div.col-xs-12.col-sm-10.col-sm-offset-1.jumbotron
    %h1 Search for Classes
    %div.row
      %div.col-xs-6.col-sm-6.col-md-offset-3
        = form_for classes_search_path, method: :get do |f|
          = text_field_tag :query, params[:query], :placeholder => "Enter search", class: 'form-control'
          = submit_tag "Search", name: nil, class: "btn btn-primary home-page"
          %br

    %ul.events
      %h2 Results for '#{params[:query]}'
      %div{:align => 'right'}
        = link_to "Back to all classes", ds_classes_path
      %br

      - if @ds_classes.present?
        = render @ds_classes.sort_by &:start_date
      - else 
        %li
          %div{:align => "center"}
            No matches. Retry the search or try a new search.

    %br
    %br
    %div{:align => 'right'}
      = link_to "Back to all classes", ds_classes_path

app/views/ds_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @ds_class.title %>
</p>

<p>
  <strong>Place:</strong>
  <%= @ds_class.place %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ds_class.description %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @ds_class.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @ds_class.end_time %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @ds_class.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @ds_class.end_date %>
</p>

<%= link_to 'Edit', edit_ds_class_path(@ds_class) %> |
<%= link_to 'Back', ds_classes_path %>

app/views/ds_classes/show.html.haml
- provide(:title, @ds_class.title)
%div.row
  %div.col-xs-12.col-sm-10.col-sm-offset-1.jumbotron
    %h1 #{@ds_class.title}
    %div.row
      %div.col-xs-12.col-sm-8
        %div.event_info
          %h3 Date
          #{@ds_class.start_date} - #{@ds_class.end_date}

          %h3 Location
          = @ds_class.place

          %h3 Description
          = @ds_class.description.html_safe
          %p
        - if logged_in? && current_user.staff
          = link_to "Roster", roster_of_ds_class_path(@ds_class)
          |
        - if logged_in? && current_user.admin
          = link_to "Edit", edit_ds_class_path(@ds_class)
          |
          = link_to "Delete", ds_class_path(@ds_class), method: :delete, data: { confirm: "Do you want to delete this class?" }
          |
          = link_to "Roster", roster_of_ds_class_path(@ds_class)
          |
          = link_to "Add time slot", add_time_slot_to_ds_class_path
          |
        = link_to "Back", ds_classes_path
      %div.col-xs-12.col-sm-4
        %h6 Class Times
        - if @ds_class.class_slots.any?
          %ol.time_slots
            = render @class_slots
          = will_paginate @class_slots

app/views/ds_classes/show_roster.html.haml
- provide(:title, 'Class Roster')

%div.row
  %div.col-xs-12.col-sm-10.col-sm-offset-1.jumbotron
    - if logged_in? && (current_user.admin || current_user.staff)
      %h1= @ds_class.title
      %ul#details.col-xs-12.col-md-12
        #{@ds_class.start_date} - #{@ds_class.end_date}
        %br
          #{@ds_class.place}
          %br
            %br
              - @ds_class.class_slots.each do |class_slot|
                %li
                  = render class_slot.days.reverse
                  %br
                  #{class_slot.start_time.strftime("%I:%M %p")} - #{class_slot.end_time.strftime("%I:%M %p")}
                %table.table
                  %tr
                    %th.col-xs-2
                    %th.col-xs-2 Name
                    %th.col-xs-2 Email
                    %th.col-xs-2 Phone
                    %th.col-xs-2 Emerg. Phone
                  - class_slot.users.each do |user|
                    %tr
                      - if user.appointment_class(class_slot).is_checkedin
                        %td= link_to "Checked", root_path, class: "btn btn-primary disabled home-page"
                      - else
                        %td= link_to "Check in", checkin_class_path(:id => user.id, :class_slot_id => class_slot.id, :ds_class_id => @ds_class.id), class: "btn btn-primary home-page"
                      %td= link_to user.name, user
                      %td= user.email
                      %td= user.phone
                      %td= user.emergency_contact_phone
              = link_to "Back", ds_class_path(@ds_class)
    - else
      Access Denied