config/routes.rb
Rails.application.routes.draw do

  get 'days/create'

  patch 'days/destory'

  get 'class_slots/create'

  get 'class_slots/destory'

  patch 'buddy_slots/create'

  patch 'buddy_slots/edit'

  get 'buddy_slots/destory'

  resources :ds_classes

  resources :buddy_walks

  get 'articles/edit'

  get 'articles/update'

  root 'static_pages#home'

  resources :events do
    resources :time_slots, only: [:create, :destroy]
    member do
      put 'register'
      put 'unregister'
    end
  end

  resources :buddy_walks do
    resources :buddy_slots, only: [:create, :destroy]
    member do
      put 'register'
      put 'unregister'
    end
  end

  resources :ds_classes do
    resources :class_slots, only: [:create, :edit, :destroy]
    member do
      put 'register'
      put 'unregister'
    end
  end

  resources :class_slot do
    resources :days, only: [:create, :destroy]
    member do
    end
  end

  get    'home'   => 'static_pages#home'
  get    'calendar' => 'static_pages#calendar'
  get    'edit_text_box' => 'static_pages#edit_text_box'
  get    'checkin' => 'users#checkin'
  get    'checkin_class' => 'users#checkin_class'
  get    'checkin_buddy_walk' => 'users#checkin_buddy_walk'
  get    'give_staff_role' => 'users#give_staff_role'
  get    'remove_staff_role' => 'users#remove_staff_role'
  get    'schedule_buddy_walk' => 'buddy_walks#schedule'
  get    'edit_schedule_buddy_walk' => 'buddy_walks#edit_schedule'
  post    'schedule_update' => 'buddy_walks#schedule_update'
  patch    'edit_schedule_update' => 'buddy_walks#edit_schedule_update'

  get    'signup' => 'users#new'
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get     'registration_confirmation'=> 'users#registration_confirmation', as: 'reg'

  get    'searchresults_events'     => 'events#search',        as: 'events_search'
  get    'searchresults_users'      => 'users#search',         as: 'users_search'
  get    'searchresults_classes'      => 'ds_classes#search',  as: 'classes_search'
  get    'searchresults_buddy_walk_users/:id'      => 'buddy_walks#roster_search',  as: 'buddy_walk_user_search'
  
  get    'events/:id/roster'        => 'events#show_roster',   as: 'roster_of_event'
  get    'events/:id/add_time_slot' => 'events#add_time_slot', as: 'add_time_slot_to_event'

  get    'buddy_walks/:id/roster'        => 'buddy_walks#show_roster',   as: 'roster_of_buddy_walk'
  get    'add_buddy_slot' => 'buddy_walks#add_buddy_slot', as: 'add_buddy_slot_to_buddy_walks'
  get    'edit_buddy_slot' => 'buddy_walks#edit_buddy_slot', as: 'edit_buddy_slot_of_buddy_walks'

  get    'ds_classes/:id/roster'        => 'ds_classes#show_roster',   as: 'roster_of_ds_class'
  get    'ds_classes/:id/add_time_slot' => 'ds_classes#add_time_slot', as: 'add_time_slot_to_ds_class'
  
  get    'ds_classes/:class_id/class_slot/:class_slot_id/add_day'  => 'class_slots#add_day', as: 'add_day_to_class_slot'
  get    'ds_classes/:class_id/class_slot/:class_slot_id/remove_day'  => 'class_slots#remove_day', as: 'remove_day_from_class_slot'

  resources :users do
    member do
      get 'registrations' => 'users#show_registrations'
    end
  end

  resources :account_activations, only: [:new, :create, :edit, :update]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :articles, only: [:edit, :update]

end

app/models/buddy_walk.rb
class BuddyWalk < ActiveRecord::Base
  has_one :buddy_slot, dependent: :destroy
  has_many :users, through: :buddy_slot
	validates :date, presence: true

	def send_event_register_email
		EventMailer.event_register_notification(self).deliver
	end

	def self.search(search)
		where('lower(title) LIKE ? OR lower(place) LIKE ? OR lower(description) LIKE ?', 
			"%#{search.downcase}%", "%#{search.downcase}%", "%#{search.downcase}%")
	end
end

  

app/controllers/buddy_walks_controller.rb
class BuddyWalksController < ApplicationController
  before_action :logged_in_user, only: [:register, :unregister]
  before_action :admin_user,     only: [:new, :create, :edit, :update, :destroy, :add_buddy_slot, :edit_buddy_slot, :schedule_update, :schedule, :edit_schedule, :edit_schedule_update]
  before_action :staff_user,     only: [:show_roster, :roster_search]

  def index
    @article = Article.find_by_id(4)
    @buddy_walks = BuddyWalk.all
  end

  def search
    @buddy_walks = BuddyWalk.all
    if params[:query]
      @buddy_walks = BuddyWalk.search(params[:query])
    else
      @buddy_walks = []
    end
  end

  def roster_search
    @buddy_walk = BuddyWalk.find(params[:id])
    if params[:query]
      @users = @buddy_walk.buddy_slot.users.search(params[:query])
    else
      @users = []
    end
  end

  def show
    @buddy_walk = BuddyWalk.find(params[:id])
    @buddy_slot = @buddy_walk.buddy_slot
  end

  def new
    @buddy_walk = BuddyWalk.new
  end

  def create
    @buddy_walk = BuddyWalk.new(buddy_walk_params)
    if @buddy_walk.save
      flash[:success] = "New Buddy Walk has been created."
      redirect_to buddy_walk_path(@buddy_walk)
    else
      render 'new'
    end
  end

  def edit
    @buddy_walk = BuddyWalk.find params[:id]
  end

  def update
    @buddy_walk = BuddyWalk.find params[:id]
    if @buddy_walk.update_attributes(buddy_walk_params)
      flash[:success] = "Buddy walk deal updated."
      redirect_to @buddy_walk
    else
      render 'edit'
    end
  end

  def destroy
    @buddy_walk = BuddyWalk.find params[:id]
    if @buddy_walk.buddy_slot != nil
      @buddy_walk.buddy_slot.users.each do |user|
        EventMailer.event_cancellation_buddy(user, @buddy_walk.buddy_slot).deliver
      end
    end
    @buddy_walk.destroy
    flash[:info] = "BuddyWalk '#{@buddy_walk.title}' deleted."
		redirect_to buddy_walks_path
  end

  def add_buddy_slot
    @buddy_walk = BuddyWalk.all.first
    @buddy_walk.buddy_slot = BuddySlot.new
    @buddy_slot = @buddy_walk.buddy_slot
  end

  def edit_buddy_slot
    @buddy_walk = BuddyWalk.all.first
    @buddy_walk.buddy_slot = BuddySlot.new
    @buddy_slot = @buddy_walk.buddy_slot
  end

  def show_roster
    @buddy_walk = BuddyWalk.find(params[:id])
    if params[:query]
      @users = @buddy_walk.buddy_slot.users.search(params[:query])
    else
      @users = @buddy_walk.buddy_slot.users
    end
  end

  def register
    buddy_slot = BuddySlot.find(params[:buddy_slot_id])
    if current_user.buddy_slots.include?(buddy_slot)
      redirect_to registrations_user_path(current_user)
    else
      buddy_slot.save

      EventMailer.event_registration_buddy(current_user, buddy_slot).deliver

      current_user.buddy_slots << buddy_slot
      flash[:success] = "You have successfully registered the event."
      redirect_to registrations_user_path(current_user)
    end
  end
  
  def unregister
    buddy_slot = BuddySlot.find(params[:buddy_slot_id])
    if !current_user.buddy_slots.include?(buddy_slot)
      redirect_to registrations_user_path(current_user)
    else
      current_user.appointment_buddy(buddy_slot).destroy
      current_user.buddy_slots.delete(buddy_slot)
      flash[:success] = "You have successfully unregistered for this event."
      redirect_to registrations_user_path(current_user)
    end
  end

  def schedule
    @buddy_walk = BuddyWalk.new
  end

  def schedule_update
    @buddy_walk = BuddyWalk.new(buddy_walk_params)
    first = BuddyWalk.all.first
    @buddy_walk.date = first.date
    @buddy_walk.place = first.place
    if first.buddy_slot != nil
      @buddy_walk.buddy_slot = BuddySlot.new
      @buddy_walk.buddy_slot.start_time = first.buddy_slot.start_time
      @buddy_walk.buddy_slot.end_time = first.buddy_slot.end_time
      @buddy_walk.buddy_slot.save
    end 
    if @buddy_walk.save
      flash[:success] = "New Buddy Walk Deal has been created."
      redirect_to buddy_walk_path(@buddy_walk)
    else
      flash[:info] = "New Buddy walk deal did not save!"
      redirect_to schedule_buddy_walk_path
    end
  end

  def edit_schedule
    @buddy_walk = BuddyWalk.all.first
  end

  def edit_schedule_update
    BuddyWalk.all.each do |buddy_walk|
      buddy_walk.update_attributes(buddy_walk_params)
    end
    flash[:success] = "Buddy Walk schedule updated."
    redirect_to buddy_walks_path
  end

  private

    def buddy_walk_params
      params.require(:buddy_walk).permit(:title, :date, :place, :description)
    end

end

app/helpers/buddy_walks_helper.rb
module BuddyWalksHelper
end

app/views/buddy_walks/_buddy_walk.html.haml
%li
  %div{:align => "left"}
    #{buddy_walk.date}:
    %div{:align => "center"}
      = link_to buddy_walk.title, buddy_walk
      - if logged_in? && current_user.admin?
        %div{:style => "float: right"}
          = link_to "Edit", edit_buddy_walk_path(buddy_walk)
          |
          = link_to "Delete", buddy_walk, method: :delete, data: { confirm: "You sure?" } 

app/views/buddy_walks/_form.html.erb
<%= form_for(@buddy_walk) do |f| %>
  <% if @buddy_walk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@buddy_walk.errors.count, "error") %> prohibited this buddy_walk from being saved:</h2>

      <ul>
      <% @buddy_walk.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buddy_walks/add_buddy_slot.html.haml
- provide(:title, "Add time slot to Buddy walk")
%div.row
  %div.col-xs-12.col-sm-10.col-sm-offset-1.jumbotron
    %div.event_info
      %h1 Add time slot to Buddy walk
      %div.row
        %div.col-xs-12.col-md-6.col-md-offset-3
          - if logged_in? && current_user.admin
            = form_for(@buddy_slot, url: {controller: :buddy_slots, action: :create}) do |f|
              = render 'shared/error_messages', object: f.object

              = f.label :start_time, "Start Time (HH:MM AM/PM)"
              = f.text_field :start_time, class: "timepicker", :placeholder => "  Ex: 12:00 AM"

              = f.label :end_time, "End Time (HH:MM AM/PM)"
              = f.text_field :end_time, class: "timepicker", :placeholder => "  Ex: 12:00 AM"

              = f.submit "Submit", class: "btn btn-primary home-page"
            %br/
            = link_to "Back", buddy_walks_path
          -else
            Access Denied

app/views/buddy_walks/edit.html.haml
- provide(:title, 'Edit Buddy Walk Deal')
%div.row
  %div.col-xs-12.col-sm-10.col-sm-offset-1.jumbotron
    %h1 Edit Buddy Walk Deal
    %div.row
      %div.col-xs-12.col-md-6.col-md-offset-3
        = form_for(@buddy_walk) do |f|
          = render 'shared/error_messages', object: f.object

          = f.label :title
          = f.text_field :title, class: 'form-control'

          = f.hidden_field :date, :value => @buddy_walk.date.strftime("   %B %_d, %Y")

          = f.hidden_field :place, :value => @buddy_walk.place

          = f.label :description
          = f.text_area :description, class: 'form-control', :placeholder => "Enter description"

          = f.submit 'Save', class: 'btn btn-primary home-page'

app/views/buddy_walks/edit_buddy_slot.html.haml
- provide(:title, "Edit time slot to Buddy walk")
%div.row
  %div.col-xs-12.col-sm-10.col-sm-offset-1.jumbotron
    %div.event_info
      %h1 Edit time slot of Buddy walk
      %div.row
        %div.col-xs-12.col-md-6.col-md-offset-3
          - if logged_in? && current_user.admin
            = form_for(@buddy_slot, url: {controller: :buddy_slots, action: :edit}) do |f|
              = render 'shared/error_messages', object: f.object

              = f.label :start_time, "Start Time (HH:MM AM/PM)"
              = f.text_field :start_time, class: "timepicker", :placeholder => "  Ex: 12:00 AM"

              = f.label :end_time, "End Time (HH:MM AM/PM)"
              = f.text_field :end_time, class: "timepicker", :placeholder => "  Ex: 12:00 AM"

              = f.submit "Submit", class: "btn btn-primary home-page"
            %br/
            = link_to "Back", buddy_walks_path
          -else
            Access Denied

app/views/buddy_walks/edit_schedule.html.haml
- provide(:title, 'Edit Buddy Walk Event Schedule')
%div.row
  %div.col-xs-12.col-sm-10.col-sm-offset-1.jumbotron
    %h1 Edit Buddy Walk Event Schedule
    %div.row
      %div.col-xs-12.col-md-6.col-md-offset-3
        = form_for(@buddy_walk, url: {controller: :buddy_walks, action: :edit_schedule_update}) do |f|
          = render 'shared/error_messages', object: f.object

          = f.hidden_field :date, :value => @buddy_walk.title

          = f.hidden_field :description, :value => @buddy_walk.description

          = f.label :date, "Date"
          = f.text_field :date, class: "datepicker", :value => @buddy_walk.date.strftime("   %B %_d, %Y"), :placeholder => "Ex: September 2, 2015"

          = f.label :place, "Location"
          = f.text_field :place, class: 'form-control', :placeholder => "Enter location"

          = f.submit 'Save', class: 'btn btn-primary home-page'

app/views/buddy_walks/index.html.haml
= provide(:title, 'Buddy Walk')
%div.row
  %div.col-xs-12.col-sm-10.col-sm-offset-1.jumbotron
    %h1 Buddy Walk
    %div.row
      - if logged_in? && current_user.admin?
        = link_to "Edit Text", { action: :edit, controller: :articles, id: 4 }, class: "btn btn-primary home-page"
      %div.col-xs-12.col-sm-10.col-sm-offset-1.jumbotron
        %div
          = @article.text.html_safe
    %br
    %ul.events
      = render @buddy_walks.sort_by{|bw| [bw.title, bw.date]}
      %br
      -if logged_in? && current_user.admin
        - if @buddy_walks.any?
          = link_to "Add new Registration Deal", schedule_buddy_walk_path
          %br
          = link_to "Change Buddy Walk Schedule", edit_schedule_buddy_walk_path
          %br
          - if @buddy_walks.first.buddy_slot == nil
            = link_to "Add time slot to buddy walk", add_buddy_slot_to_buddy_walks_path
          - else
            = link_to "Change time slot of buddy walk", edit_buddy_slot_of_buddy_walks_path
        - else
          = link_to "Schedule Buddy Walk Event", new_buddy_walk_path

app/views/buddy_walks/new.html.erb
<h1>New buddy_walk</h1>

<%= render 'form' %>

<%= link_to 'Back', buddy_walks_path %>

app/views/buddy_walks/new.html.haml
%div.row
  %div.col-xs-12.col-sm-10.col-sm-offset-1.jumbotron
    %h1 New Buddy Walk Registration Group
    %div.row
      %div.col-xs-12.col-md-6.col-md-offset-3
        = form_for(@buddy_walk) do |f|
          = render 'shared/error_messages', object: f.object

          = f.label :title
          = f.text_field :title, class: 'form-control'
        
          = f.label :date, "Date (MM-DD-YYYY)"
          = f.text_field :date, class: "datepicker", :placeholder => "  Ex: September 2, 2015"

          = f.label :place, "Location"
          = f.text_field :place, class: 'form-control', :placeholder => "Enter location"

          = f.label :description
          = f.text_area :description, class: 'form-control', :placeholder => "Enter description"

          = f.submit "Create new deal", class: "btn btn-primary home-page"

app/views/buddy_walks/print.html.haml
%div.row
	%div.col-xs-12.col-sm-10.col-sm-offset-1.jumbrotron
		%h1 #{@buddy_walk.title}

		%u1#details
			%li
				Date:
				= @buddy_walk.date
			%li
				Place:
				= @buddy_walk.place
			%li
				Description:
				= @buddy_walk.description.html_safe

		= link_to "Back", buddy_walks_path

app/views/buddy_walks/roster_search.html.haml
- provide(:title, 'Buddy walk Roster')

%div.row
  %div.col-xs-12.col-sm-10.col-sm-offset-1.jumbotron
    - if logged_in? && (current_user.admin || current_user.staff)
      %h1= @buddy_walk.title
      %div.col-xs-6.col-sm-6.col-md-offset-3
        = form_for buddy_walk_user_search_path(:id => @buddy_walk.id), method: :get do |f|
          = text_field_tag :query, params[:query], :placeholder => "Enter search", class: 'form-control'
          = submit_tag "Search", name: nil, class: "btn btn-primary home-page"
          %br
      %ul#details.col-xs-12.col-md-12
        #{@buddy_walk.date}
        %br
          #{@buddy_walk.place}
          %br
            %br
              #{@buddy_walk.buddy_slot.start_time.strftime("%I:%M %p")} - #{@buddy_walk.buddy_slot.end_time.strftime("%I:%M %p")}
              %table.table
                %tr
                  %th.col-xs-2
                  %th.col-xs-2 Name
                  %th.col-xs-2 Email
                  %th.col-xs-2 Phone
                  %th.col-xs-2 Emerg. Phone
                - @users.each do |user|
                  %tr
                    - if user.appointment_buddy(@buddy_walk.buddy_slot).is_checkedin
                      %td= link_to "Checked", root_path, class: "btn btn-primary disabled home-page"
                    - else
                      %td= link_to "Check in", checkin_buddy_walk_path(:id => user.id, :buddy_slot_id => @buddy_walk.buddy_slot.id, :buddy_walk_id => @buddy_walk.id), class: "btn btn-primary home-page" 
                    %td= link_to user.name, user
                    %td= user.email
                    %td= user.phone
                    %td= user.emergency_contact_phone
            = link_to "Back", buddy_walk_path(@buddy_walk)
    - else
      Access Denied

app/views/buddy_walks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @buddy_walk.title %>
</p>

<p>
  <strong>Place:</strong>
  <%= @buddy_walk.place %>
</p>

<p>
  <strong>Description:</strong>
  <%= @buddy_walk.description %>
</p>

<%= link_to 'Edit', edit_buddy_walk_path(@buddy_walk) %> |
<%= link_to 'Back', buddy_walks_path %>

app/views/buddy_walks/show.html.haml
%div.row
  %div.col-xs-12.col-sm-10.col-sm-offset-1.jumbotron
    %h1 #{@buddy_walk.title}
    %div.row
      %div.col-xs-12.col-sm-8
        %div.buddy_walk_info
          %h3 Date
          = @buddy_walk.date

          %h3 Location
          = @buddy_walk.place

          %h3 Description
          = @buddy_walk.description.html_safe
          %p
        - if logged_in? && current_user.staff
          = link_to "Roster", roster_of_buddy_walk_path(@buddy_walk)
          |
        - if logged_in? && current_user.admin
          = link_to "Edit", edit_buddy_walk_path(@buddy_walk)
          |
          = link_to "Delete", buddy_walk_path(@buddy_walk), method: :delete, data: { confirm: "Do you want to delete this deal?" }
          |
          -if @buddy_walk.buddy_slot != nil
            = link_to "Roster", roster_of_buddy_walk_path(@buddy_walk)
            |
        = link_to "Back", buddy_walks_path
      %div.col-xs-12.col-sm-4
        - if @buddy_slot != nil
          %ol.time_slots
            = render @buddy_slot

app/views/buddy_walks/show_roster.html.haml
- provide(:title, 'Buddy walk Roster')

%div.row
  %div.col-xs-12.col-sm-10.col-sm-offset-1.jumbotron
    - if logged_in? && (current_user.admin || current_user.staff)
      %h1= @buddy_walk.title
      %div.col-xs-6.col-sm-6.col-md-offset-3
        = form_for buddy_walk_user_search_path(:id => @buddy_walk.id), method: :get do |f|
          = text_field_tag :query, params[:query], :placeholder => "Enter search", class: 'form-control'
          = submit_tag "Search", name: nil, class: "btn btn-primary home-page"
          %br
      %ul#details.col-xs-12.col-md-12
        #{@buddy_walk.date}
        %br
        #{@buddy_walk.place}
        %br
        %br
        #{@buddy_walk.buddy_slot.start_time.strftime("%I:%M %p")} - #{@buddy_walk.buddy_slot.end_time.strftime("%I:%M %p")}
        %table.table
          %tr
            %th.col-xs-2
            %th.col-xs-2 Name
            %th.col-xs-2 Email
            %th.col-xs-2 Phone
            %th.col-xs-2 Emerg. Phone
          - @users.each do |user|
            %tr
              - if user.appointment_buddy(@buddy_walk.buddy_slot).is_checkedin
                %td= link_to "Checked", root_path, class: "btn btn-primary disabled home-page"
              - else
                %td= link_to "Check in", checkin_buddy_walk_path(:id => user.id, :buddy_slot_id => @buddy_walk.buddy_slot.id, :buddy_walk_id => @buddy_walk.id), class: "btn btn-primary home-page" 
              %td= link_to user.name, user
              %td= user.email
              %td= user.phone
              %td= user.emergency_contact_phone
        = link_to "Back", buddy_walk_path(@buddy_walk)
    - else
      Access Denied